// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesk1OvbwUV1QivZq6p8BDLRVTA8tqr1M',
    appId: '1:869256777076:web:b382d3890f64f2eddeb021',
    messagingSenderId: '869256777076',
    projectId: 'tobeto-2a-firebase',
    authDomain: 'tobeto-2a-firebase.firebaseapp.com',
    storageBucket: 'tobeto-2a-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAT-YkNDqGw_V33_UNmBYNup5ZjmgX24E',
    appId: '1:869256777076:android:dbe8c9050e7e10b6deb021',
    messagingSenderId: '869256777076',
    projectId: 'tobeto-2a-firebase',
    storageBucket: 'tobeto-2a-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWun3MqaqrkbwEYZR3COqtAD4SfVcaoJU',
    appId: '1:869256777076:ios:86e193a4051591aedeb021',
    messagingSenderId: '869256777076',
    projectId: 'tobeto-2a-firebase',
    storageBucket: 'tobeto-2a-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWun3MqaqrkbwEYZR3COqtAD4SfVcaoJU',
    appId: '1:869256777076:ios:86e193a4051591aedeb021',
    messagingSenderId: '869256777076',
    projectId: 'tobeto-2a-firebase',
    storageBucket: 'tobeto-2a-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBesk1OvbwUV1QivZq6p8BDLRVTA8tqr1M',
    appId: '1:869256777076:web:ee2db5c9099d5bb4deb021',
    messagingSenderId: '869256777076',
    projectId: 'tobeto-2a-firebase',
    authDomain: 'tobeto-2a-firebase.firebaseapp.com',
    storageBucket: 'tobeto-2a-firebase.appspot.com',
  );
}
